v0.2.3 (#10) - UI improvement
Changelog:

* Exit through Ctrl-C is now supported

* Major change in UI:

** PM button for choosing who to PM to. No need to type @peerID

** Explorer button for choosing path to share. This merely selects, user must still confirm and press Send

** PM and Explorer button can be used simultaneously for sending file/directory privately to a peer

** Chat button for inspecting entire chat in the present session. Can also be used to clear the input area

diff --git a/ipfs-chat b/ipfs-chat
--- a/ipfs-chat
+++ b/ipfs-chat
@@ -2,7 +2,7 @@
 # Details: See info and usage functions below
 # Warning: This code closes all background processes in the current terminal session on exit # TODO:
 
-export version="0.2.2 (alpha)"
+export version="0.2.3 (alpha)"
 
 info(){
   # Brief: Info about ipfs-chat
@@ -84,11 +84,6 @@ dep_check(){
     echo -e "Ref: https://command-not-found.com/dialog\n"
     quit="yes"
   fi
-  if ! command -v setsid &>/dev/null; then
-    echo -e "Required: setsid\nSource: Native package repository"
-    echo -e "Ref: https://command-not-found.com/setsid\n"
-    quit="yes"
-  fi
   if ! command -v curl &>/dev/null; then
     echo -e "Required: curl\nSource: Native package repository"
     echo -e "Ref: https://command-not-found.com/curl\n"
@@ -121,6 +116,7 @@ win2lin_path(){
   # Usage: win2lin_path <path> ##or## win2lin_path < file_containing_path
   # The input can be formatted freely. Path may contain spaces not esacaped by \. Quotes may or may not be used for Win paths
   local input="${@}"; [[ -n "${input}" ]] || read -r input # Backslash not special due to -r
+  input="${input%/}" # Trailing slash removal, if any
   if ! [[ "${input}" == ~* ]]; then
     local quote_less="$(echo "${input//\\/\\\\}" | xargs)" # xargs does quote removal. To save backslash, escaped 'em
     wslpath "${quote_less}" && return
@@ -206,7 +202,7 @@ ipfs_config(){
   # Brief: Configure IPFS node
   # Note: Use random ports for everything so that multiple IPFS nodes can coexist on the same machine
   # Note: Most configs below are for reducing bandwidth/CPU/disk usage
-  echo -ne "Status: Configuring IPFS node...\r"
+  echo "Status: Configuring IPFS node..."
   if ! ipfs id &>/dev/null; then
     (ipfs init --profile lowpower && ipfs config profile apply randomports) >/dev/null || \
       { echo "Error: Failed to create IPFS repo at ${IPFS_PATH}"; exit 1;}
@@ -230,21 +226,21 @@ ipfs_config(){
     rm -f "${sess_peers}" "${sess_uplds}"
     ipfs pin ls --type=recursive --quiet | xargs -n1 ipfs pin rm # Remove stale pins to destress reprovider
   fi &>/dev/null # Can't be non-blocking. Otherwise launching IPFS daemon shows, "ERROR: lock ... :someone else has lock"
-  echo -ne "$(tput ed)Status: Stale pins removed\r"
 
-  export global_fs="${HOME}/.filestore-ipfs-chat" # For multinode deduplication. UL files named after SHA1, DL files after CID
-  mkdir -p "${global_fs}"; local global_fs_MB="$(du -BM "${global_fs}" | awk '{print $1}' | tr -d M)"
-  # Cleanup global cache when disk usage exceeds 1 GB
+  export global_fs="${HOME}/.filestore-ipfs-chat"; mkdir -p "${global_fs}"
+  # For multinode deduplication. UL files named after SHA1, DL files after CID  
+  # Cleanup global cache in background when disk usage exceeds 1 GB
   # ICGFS: IPFS_CHAT_GLOBAL_FILESTORE_SIZE in MB (type: integer)
-  if ((global_fs_MB > "${ICGFS:=1024}")); then
+  if (("$(du -BM "${global_fs}" | awk '{print $1}' | tr -d M)" > "${ICGFS:=1024}")); then
     flock -n "${global_fs}" rm -rf "${global_fs}"/*
-  fi
+  fi &
   
+  echo "$(tput cuu1; tput ed)Status: Preparing the IPFS config file..."  
   ipfs config --bool Swarm.DisableBandwidthMetrics "${disable_bandwidth_metrics:-true}"
-
   case "${connect_mode}" in
     LAN)
-      ipfs config --bool Discovery.MDNS.Enabled true
+      ipfs config profile apply local-discovery &>/dev/null # Revert changes done by Server profile
+      #ipfs config --bool Discovery.MDNS.Enabled true
       ipfs bootstrap rm all &>/dev/null # For faster startup
       # Disable NAT traversal
       ipfs config --bool Swarm.DisableNatPortMap true
@@ -254,9 +250,12 @@ ipfs_config(){
       ;;
     WAN | *)
       if [[ "${connect_mode}" == WAN ]]; then
-        ipfs config --bool Discovery.MDNS.Enabled false
+        ipfs config profile apply server &>/dev/null
+        # Server profile disables swarm connecting to private IPs. Doesn't announce own private IPs. Disables MDNS discovery
+        #ipfs config --bool Discovery.MDNS.Enabled false
       else
-        ipfs config --bool Discovery.MDNS.Enabled true
+        ipfs config profile apply local-discovery &>/dev/null # Revert changes done by Server profile
+        #ipfs config --bool Discovery.MDNS.Enabled true
       fi
       ipfs bootstrap add default &>/dev/null # For WAN-DHT
       # For NAT traversal
@@ -267,25 +266,27 @@ ipfs_config(){
       ;;
   esac
 
+  echo "$(tput cuu1; tput ed)Status: Configuring ports..."
   pscan(){
     # Brief: Give an unused, random, local TCP port except the one passed as argument
-    command -v nc &>/dev/null || return 1 # TODO: For machines with no nc consider socat
     local port except="${1}"
-    for port in $(seq 49152 65535 | tac);do
+    while port="$(( 0x"$(dd if=/dev/urandom bs=2 count=1 2> /dev/null | xxd -p)" - 1 ))";do
       ((port!=except)) || continue
-      ! nc -z localhost "${port}" && echo "${port}" && return # TODO: For machines with no nc consider socat
+      nc -z localhost "${port}" || break
     done
+    echo "${port}"
   } 2>/dev/null; export -f pscan
   local API_port="$(pscan)"; ipfs config Addresses.API "/ip4/127.0.0.1/tcp/${API_port:=5001}"
   local gateway_port="$(pscan "${API_port}")"; ipfs config Addresses.Gateway "/ip4/127.0.0.1/tcp/${gateway_port:=8080}"
 
+  echo "$(tput cuu1; tput ed)Status: Getting node online (launching IPFS daemon)..."
   until ipfs swarm peers;do
-    setsid --fork flock -sF "${global_fs}" ipfs daemon --enable-pubsub-experiment --enable-namesys-pubsub # Non-blocking due to --fork
-    # setsid makes sure daemon runs in a separate session, such that `pkill -s 0` does not kill it.
+    flock -sF "${global_fs}" ipfs daemon --enable-pubsub-experiment --enable-namesys-pubsub &   
     # TODO: Once main exit trap is refactored, perhaps we can do away with setsid.
     sleep 0.1
   done &>/dev/null
-  echo "$(tput ed)Status: IPFS node is configured"
+  rm -f "${IPFS_PATH}/config-pre-"* # Remove config backup files generated with `ipfs config profile apply`
+  echo "$(tput cuu1; tput ed)Status: IPFS node is configured"
   declare -rigx daemon_launch_time="${EPOCHSECONDS}"
   
   export selfID="$(ipfs config Identity.PeerID)"; cache_peer "${selfID}"
@@ -293,22 +294,6 @@ ipfs_config(){
 } >&2; export -f ipfs_config
 
 ipfs_config
-
-safe_gc(){
-  # Brief: Remove blocks that are not pinned. Difference with `ipfs repo gc` is that this removes only those blocks
-  # that are there when function is called, even if the actual cleanup takes time. Also, can check lock for added safety.
-  # Usage: safe_gc [<lock-file>]
-  # Note: Requires IPFS to be online otherwise exit with error
-  ipfs swarm peers && flock -n 3 || return 1
-  local lock="${1}"
-  if [[ -n "${lock}" ]]; then
-    flock -n "${lock}" ipfs refs local # This doesn't take much time
-  else
-    ipfs refs local
-  fi | xargs -n1 ipfs block rm # This is the time consuming part
-} &>/dev/null 3<"${IPFS_PATH}/config"; export -f safe_gc
-
-safe_gc &
 
 config(){
   # Brief: General config. Compute and export variables. Setup tmp dir and runtime filesystem.
@@ -347,6 +332,22 @@ config(){
 } >&2; export -f config
 
 config
+
+safe_gc(){
+  # Brief: Remove blocks that are not pinned. Difference with `ipfs repo gc` is that this removes only those blocks
+  # that are there when function is called, even if the actual cleanup takes time. Also, can check lock for added safety.
+  # Usage: safe_gc [<lock-file>]
+  # Note: Requires IPFS to be online
+  flock -n 3 || return 1
+  local lock="${1}"
+  if [[ -n "${lock}" ]]; then
+    flock -n "${lock}" ipfs refs local # This doesn't take much time
+  else
+    ipfs refs local
+  fi | xargs -n1 ipfs block rm # This is the time consuming part
+} &>/dev/null 3<"${IPFS_PATH}/config"; export -f safe_gc
+
+safe_gc & echo "${!}" >> "${bg_pids}"
 
 identity(){
   # Brief: Generate key-pair. Claim nick & pubkey using IPNS.
@@ -390,17 +391,20 @@ connect_peer(){
   # Brief: Connect to peer ID or multiaddress provided as argument
   # TODO: Simplify and economize
   local input="${1}" peerID="${1##*/}" multiaddress
-  if [[ "${peerID}" != "${input}" ]]; then
+  if [[ "${peerID}" == "${selfID}" ]]; then
+    return 0
+  elif [[ "${peerID}" != "${input}" ]]; then
     multiaddress="${input}"
   else
     multiaddress="/p2p/${peerID}"
   fi
-  if [[ "${peerID}" == "${selfID}" ]] || (ipfs swarm peers | grep -q -m1 "${peerID}") || ipfs swarm connect "${multiaddress}"; then
+  if ipfs swarm connect "${multiaddress}"; then
+    # Swarm connect autochecks whether peerID is already connected. If not, only then tries multiaddress
     for multiaddress in $(ipfs swarm peers | grep "${peerID}"); do
       cache_peer "${multiaddress}" # Add multiaddress of both peer and any relay it is accessed through
     done
   else
-    cache_peer "${multiaddress}"
+    cache_peer "${peerID}"
     return 1
   fi
 } &>/dev/null; export -f connect_peer
@@ -408,6 +412,7 @@ connect_peer(){
 peer_pubkey_nick(){
   # Brief: Import pubkey of peer ID or multiaddress passed as argument and output its nick. Flag -n to force IPNS update (nocache).
   # TODO: TBD: peer_pubkey=CID_peerID
+  # TODO: Optimize performance / eliminate repetitions with lock. Solve sometimes peer_nick not showing
   local OPTIND=1 opt nocache
   getopts n opt; [[ "${opt}" == "n" ]] && nocache="--nocache"
   local multiaddress="${!OPTIND}"
@@ -424,6 +429,7 @@ peer_pubkey_nick(){
     gnupg --no-default-keyring --keyring "${peer_kbx}" --import "${peer_pubkey}" || rm -f "${peer_pubkey}"
   fi &>/dev/null
   if peer_nick="$(tail -n1 "${peer_pubkey}")"; then
+    [[ -n "${peer_nick}" ]] || return 1 # TODO: Understand how peer_nick can ever be empty
     local peer_buff="${peer_nick} @${peerID:${#peerID}-6:6}"
     grep -q -m1 "${peer_buff}" "${peers}" || flock "${peers}" echo "${peer_buff}" >> "${peers}" # Live update of online-peers window
     flock "${peers_buffer}" echo "${peer_buff}" >> "${peers_buffer}"
@@ -535,7 +541,7 @@ peering_daemon(){
   local -A peerID_list # Associative array
 
   local -r start_peer_discov="${EPOCHSECONDS}"
-  while ipfs swarm peers &>/dev/null;do # Do as long as IPFS daemon is alive
+  while :;do
     dht_ops_pid=() # Stores pid's of background DHT operations executing in the current pass
     local timestamp="${EPOCHSECONDS}" # Current Unix time
     local nonce="$(hmac "${broadcast}" "$((timestamp/120))" | ipfs add -Q --stdin-name='Rendezvous')" # Announce time based nonce
@@ -624,10 +630,12 @@ send(){
 
 ui(){
   # Brief: UI event-loop. Window numbering: 1(Top Left) 2(Top Right) 3(Spanning Bottom)
+    local PM_buffer="$(tmpgen)" file_buffer="$(tmpgen)"
     local input_help="\Zb\Z4Nick: \Zu\Z0${nick}\Zn \Zb\Z4peerID: \Zu\Z0@${selfID:${#selfID}-6:6}\Zn
-\Zb\Z4General-Message:\Z1 Simply type in your text & press Enter or Send\Zn
-\Zb\Z4Fle-sharing:\Z2 Drag-n-drop file or directory, or use the File explorer button, or type in path\Zn
-\Zb\Z4Private-Message:\Z5 Put recipient's @peerID followed by a space before your text or file-path\Zn"
+\Zb\Z4General-Message:\Z1 Type, then \Z4Send\Z1 (or press \Z4Enter\Z1)\Zn
+\Zb\Z4Fle-sharing:\Z2 Drag-n-drop file/directory, or use \Z4Explorer\Zn
+\Zb\Z4Private-Message:\Z5 Select peer using \Z4PM\Z5, then type and \Z4Send\Zn"
+
   while :;do
     # Dimensions are computed just before calling `dialog` to accomodate for the latest terminal window size changes
     local tty_height="$(tput lines)" tty_width="$(tput cols)"
@@ -640,35 +648,43 @@ ui(){
       lwrap "${chat}"
       local last_win1_width="${win1_width}"
     fi # Conditionality decreases lag between pressing Send and subsequent chatbox update
-    dialog --keep-tite \
+
+    DIALOG_CANCEL=4 dialog --keep-tite \
       --title "Room: ${room}" --begin 0 0 --tailboxbg "${chat}" "${win12_height}" "${win1_width}" \
       --and-widget \
       --title "Online-peers" --begin 0 "${win1_width}" --tailboxbg "${peers}" "${win12_height}" "${win2_width}" \
       --and-widget --colors \
       --no-shadow --title "Press Esc to exit" --begin "$((tty_height-win3_height))" 0 \
-      --ok-label "Send" --cancel-label "File explorer" \
-      --extra-button --extra-label "Inspect chat" \
-      --help-button --help-label "Inspect peers" \
-      --inputbox "${input_help}" "${win3_height}" "${win3_width}" \
+      --ok-label "Send" --cancel-label "Explorer" \
+      --extra-button --extra-label "Chat" \
+      --help-button --help-label "PM" \
+      --inputbox "${input_help}" "${win3_height}" "${win3_width}" "$(cat "${PM_buffer}" "${file_buffer}")" \
       2> "${input}"
       local exit_code=$?
+
       mv -f "${peers_ready}" "${peers}" &>/dev/null # Refresh online-peers
+
       case "${exit_code}" in
-        0) send ;; # Button: Send
-        1) # Button: Clear
-           dialog --keep-tite --title "Press Spacebar to autocomplete or select/copy" --begin 0 0 \
-           --fselect "${PWD}" "${win12_height}" "${tty_width}" 2> "${input}" \
-           && send
+        0) # Button: Send
+           send 
+           : > "${PM_buffer}"; : > "${file_buffer}"
            ;;
-        2) # Button: Inspect peers
-           dialog --keep-tite --no-shadow --exit-label "Back"\
-           --title "Online-peers" --begin 0 0 --textbox "${peers}" "${tty_height}" "${tty_width}"
+        2) # Button: PM
+           dialog --keep-tite --no-shadow --exit-label "Back" --ok-label "Select" \
+           --title "Online-peers" --begin 0 0 --menu "Choose peer" "${tty_height}" "${tty_width}" "${tty_height}" \
+           $(awk '{print $2,$1}' "${peers}") 2> "${PM_buffer}" &&  echo -n ' ' >> "${PM_buffer}"
            ;;
-        3) # Button: Inspect chat
+        3) # Button: Chat
            dialog --keep-tite --no-shadow --exit-label "Back"\
            --title "Room: ${room}" --begin 0 0 --textbox "${chat}" "${tty_height}" "${tty_width}"
+           : > "${PM_buffer}"; : > "${file_buffer}"
            ;;
-        *) # Esc
+        4) # Button: Explorer
+           dialog --keep-tite --colors --begin 0 0 \
+           --title "Help: \Z1Tab\Zn for choosing window; \Z1Spacebar\Zn for autocomplete or select/copy" \
+           --fselect "${PWD}/" "${win12_height}" "${tty_width}" 2> "${file_buffer}"
+           ;;
+        1 | *) # Ctrl-C or Esc
            local confirm_quit="Shared file download is in progress. Still wanna quit?"
            if ! flock -n "${dl_lock}" -c : ; then
             # Check if dl_lock is held by file_unpack or safe_gc. In the latter case, return without prompt.
