improve macos support
* sort command does not support -V option on macos
* add flock command requirement

diff --git a/ipfs-chat b/ipfs-chat
--- a/ipfs-chat
+++ b/ipfs-chat
@@ -73,7 +73,7 @@ dep_check(){
   local ipfs_version quit
   if ipfs_version=$(ipfs version --number 2>/dev/null); then
     local req_ipfs_ver=0.9.0 # Minimum ipfs-cli version required
-    [[ "$(echo -e "${ipfs_version}\n${req_ipfs_ver}" | sort -V | head -n1)" == "${req_ipfs_ver}" ]] || \
+    [[ "$(echo -e "${ipfs_version}\n${req_ipfs_ver}" | sort -t. -k1,1n -k2,2n -k3,3n | head -n1)" == "${req_ipfs_ver}" ]] || \
       { echo -e "Required: go-ipfs-cli version >= ${req_ipfs_ver}\nSuggestion: ipfs update install latest\n"; quit="yes";}
   else
     echo -e "Required: go-ipfs-cli\nSource: https://docs.ipfs.io/install/command-line/#linux\n"
@@ -87,6 +87,11 @@ dep_check(){
   if ! command -v curl &>/dev/null; then
     echo -e "Required: curl\nSource: Native package repository"
     echo -e "Ref: https://command-not-found.com/curl\n"
+    quit="yes"
+  fi
+  if ! command -v flock &>/dev/null; then
+    echo -e "Required: flock\nSource: Native package repository"
+    echo -e "Ref: https://command-not-found.com/flock\n"
     quit="yes"
   fi
   if ! command -v openssl &>/dev/null; then
