Improved peer discovery using IPNS-pubsub + Publish public multiaddress over pubsub (requiring jq)

diff --git a/ipfs-chat b/ipfs-chat
--- a/ipfs-chat
+++ b/ipfs-chat
@@ -98,6 +98,11 @@ dep_check(){
     echo -e "Ref: https://command-not-found.com/tput\n"
     quit="yes"
   fi
+  if ! command -v jq &>/dev/null; then
+    echo -e "Required: jq\nSource: Native package repository"
+    echo -e "Ref: https://stedolan.github.io/jq/download/\n"
+    quit="yes"
+  fi
   if ! command -v argon2 &>/dev/null; then
     echo -e "Required: argon2-cli\nSource: Native package repository / web (pre-compiled binary or build from source)"
     echo -e "Ref: https://command-not-found.com/argon2"
@@ -225,7 +230,7 @@ ipfs_config(){
   if ! ipfs swarm peers; then
     rm -rf "${IPFS_PATH}/room#"*
     rm -f "${sess_peers}" "${sess_uplds}"
-    ipfs pin ls --type=recursive --quiet | xargs -r -n1 ipfs pin rm # Remove stale pins to destress reprovider
+    ipfs pin ls --type=recursive --quiet | xargs -r -n1 -P0 ipfs pin rm # Remove stale pins to destress reprovider
   fi &>/dev/null # Can't be non-blocking. Otherwise launching IPFS daemon shows, "ERROR: lock ... :someone else has lock"
 
   export global_fs="${HOME}/.filestore-ipfs-chat"; mkdir -p "${global_fs}"
@@ -542,6 +547,8 @@ peering_daemon(){
   local -A peerID_list # Associative array
 
   local -r start_peer_discov="${EPOCHSECONDS}"
+  # Subscribe to common topics over IPNS pubsub so that peer discovery becomes faster.
+  (ipfs bootstrap | grep -o '[[:alnum:]]*$' | xargs -n1 -I{} -P0 ipfs name resolve --dhtt=1s /ipns/{}) &
   while :;do
     dht_ops_pid=() # Stores pid's of background DHT operations executing in the current pass
     local timestamp="${EPOCHSECONDS}" # Current Unix time
@@ -557,7 +564,8 @@ peering_daemon(){
     # Makes things concurrent. Note: Without the `ipfs dht` timeout, `ps` would be replete with older `cat` and `ipfs dht`
 
     [[ -n "${dht_ops_pid}" ]] && wait "${dht_ops_pid[@]}" # Wait till all DHT operations are complete
-    ipfs id "${selfID}" -f="<addrs>\n" | xargs -n1 -0 ipfs pubsub pub "${broadcast}" # Announce own multiaddresses
+    ipfs id "${selfID}" -f="<addrs>\n" | grep -vf <(ipfs diag sys | jq -r .net.interface_addresses[]) | \
+      xargs -n1 -r -0 ipfs pubsub pub "${broadcast}" # Announce own public multiaddresses over pubsub
     ipfs pin rm "${nonce}" &>/dev/null & # Otherwise reprovider will continue announcing stale nonce. Pin still necessary to save from auto-GC
     flock "${peers_buffer}" sort -uo "${peers_buffer}" "${peers_buffer}" && mv "${peers_buffer}" "${peers_ready}" # In-place sort followed by atomic move. -u defends against peers_buffer containing repetitions
     if ((EPOCHSECONDS-start_peer_discov > 30)); then
